/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class polyray_audio_NativeDCDBREffect */

#ifndef _Included_polyray_audio_NativeDCDBREffect
#define _Included_polyray_audio_NativeDCDBREffect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     polyray_audio_NativeDCDBREffect
 * Method:    setCollectorSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_polyray_audio_NativeDCDBREffect_setCollectorSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     polyray_audio_NativeDCDBREffect
 * Method:    applyDBR
 * Signature: ([F[F[FI)V
 */
JNIEXPORT void JNICALL Java_polyray_audio_NativeDCDBREffect_applyDBR
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jfloatArray, jint);

/*
 * Class:     polyray_audio_NativeDCDBREffect
 * Method:    setSamples
 * Signature: ([F[F[II)V
 */
JNIEXPORT void JNICALL Java_polyray_audio_NativeDCDBREffect_setSamples
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
