/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class polyray_systems_jds_JDS */

#ifndef _Included_polyray_systems_jds_JDS
#define _Included_polyray_systems_jds_JDS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     polyray_systems_jds_JDS
 * Method:    setup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_polyray_systems_jds_JDS_setup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     polyray_systems_jds_JDS
 * Method:    setActivity
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_polyray_systems_jds_JDS_setActivity
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     polyray_systems_jds_JDS
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_polyray_systems_jds_JDS_update
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
