/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class polyray_WallpaperWindow */

#ifndef _Included_polyray_WallpaperWindow
#define _Included_polyray_WallpaperWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     polyray_WallpaperWindow
 * Method:    createWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_polyray_WallpaperWindow_createWindow
  (JNIEnv *, jclass);

/*
 * Class:     polyray_WallpaperWindow
 * Method:    swapBuffers
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_polyray_WallpaperWindow_swapBuffers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     polyray_WallpaperWindow
 * Method:    deleteWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_polyray_WallpaperWindow_deleteWindow
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
